config/routes.rb
Rails.application.routes.draw do
  # get 'pages/dashboard'
  # get 'pages/users'
  get 'pages/advisors'
  get 'pages/show_advisor/:id', to: 'pages#show_advisor', as: 'show_advisor'
  # get 'users/advisors'

  devise_for :advisors, controllers: {
    sessions: 'advisors/sessions',
    registrations: 'advisors/registrations'
  }

  resources :advisors do
    resources :appointment_types
  end


  resources :appointments do
    patch :update_status, on: :member
  end

  resources :advisors do
    resources :appointment_types
    resources :appointments
    resources :availabilities
  end



  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/pages/_appointment_form_html.erb
<h1 class="text-lime-400/100">SHOW de L'ADVISOR</h1>

<div class="container">
  <div class="advisor-appoint">
    <img src="https://source.unsplash.com/random/?portrait" alt="Advisor">
    <div class="advisor-inf">
      <h2><%= "#{@advisor.first_name} #{@advisor.last_name}" %></h2>
      <h4><%= @advisor.bio %></h4>
    </div>
  </div>

  <%# <%= link_to "Make an appointment", new_advisor_appointment_path(advisor_id: @advisor.id) %>
  <%= link_to 'New Appointment Test', new_advisor_appointment_path(@advisor) %>
  <button data-modal-target="select-modal" data-modal-toggle="select-modal" class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button">
      Make An Appointment
  </button>

  <!-- Main modal -->
  <div id="select-modal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
      <div class="largeur-modal relative p-4 w-full max-w-2xl max-h-full">
          <!-- Modal content -->
          <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
              <!-- Modal header -->
              <div class="flex items-center justify-evenly p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                  <div class="form-header flex gap-3 text-xs text-center">
                    <span class="stepIndicator  flex-1 pb-8 relative">Appointment </span>
                    <span class="stepIndicator  flex-1 pb-8 relative">Date </span>
                    <span class="stepIndicator  flex-1 pb-8 relative">Recap</span>
                  </div>
                  <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm h-8 w-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="select-modal">
                      <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                      </svg>
                      <span class="sr-only">Close modal</span>
                  </button>
              </div>
              <!-- Modal body -->
              <%# <form id="appointmentForm" class="p-12 shadow-md rounded-2xl bg-white mx-auto border-solid border-2 border-gray-100 mb-8" action="#!"> %>
              <%= form_for(Appointment.new, url: advisor_appointments_path(@advisor), id:"appointmentForm", class:"p-12 shadow-md rounded-2xl bg-white mx-auto border-solid border-2 border-gray-100 mb-8", action:"#!") do |f| %>
                <%= f.fields_for :appointment do |appointment_fields| %>
                  <div class="step p-4 md:p-5">
                      <p class="text-gray-500 dark:text-gray-400 mb-4">Select your appointment type:</p>
                      <ul class="space-y-4 mb-4">
                        <% @appointment_types.each do |appointment_type| %>
                          <li>
                            <input type="radio" id="appointment_type_<%=appointment_type.id%>" name="appointment_type" value="<%=appointment_type.id%>" class="appointment-radio hidden" >
                            <label for="appointment_type_<%=appointment_type.id%>" class="appointment-label inline-flex items-center justify-between w-full p-5 text-gray-900 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-500 hover:text-gray-900 hover:bg-gray-100 dark:text-white dark:bg-gray-600 dark:hover:bg-gray-500">
                                <div class="block">
                                    <div class="w-full text-lg font-semibold"><%= appointment_type.name %></div>
                                    <div class="w-full text-gray-500 dark:text-gray-400"><%= appointment_type.duration %> min</div>
                                </div>
                                <svg class="w-4 h-4 ms-3 rtl:rotate-180 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/></svg>
                            </label>
                          </li>
                        <% end %>
                      </ul>
                  </div>

                  <!-- step two -->
                  <div class="step">
                      <p class="text-md text-gray-700 leading-tight text-center mt-8 mb-2">Select your date</p>
                      <div class="calendar" id="calendar">

                        <div class="week-days-container">
                          <div class="days-container">
                            <i class="arrow fa-solid fa-arrow-left" id="left"></i>
                            <% @week_dates.each do |day_name, date| %>
                              <div class="day-selector">
                                <div class="date-info">
                                  <p class="day-pick"><%= day_name %></p>
                                  <p class="date"><%= date.strftime('%d-%b') %></p>
                                </div>
                                <ul class="time-slots">
                                  <% @advisor.availabilities.each do |availability| %>
                                    <% availability.time_slots_day(date).each do |slot| %>
                                      <li>
                                        <% if slot != "none" %>
                                          <input type="radio" name="advisor-hours" id="advisor_hours_<%= slot %>_<%= date.strftime('%Y-%m-%d') %>" value="<%= slot %>"  class="advisor-hours">
                                          <label class="hour-slot" for="advisor_hours_<%= slot %>_<%= date.strftime('%Y-%m-%d') %>">
                                            <div class="block">
                                              <div class="time w-full"><%= slot %></div>
                                            </div>
                                          </label>
                                        <% else %>
                                          <input class="none-advisor-hours" type="radio" name="advisor-hours" id="advisor_hours_<%= slot %>_<%= date.strftime('%Y-%m-%d') %>" value="<%= slot %>" disabled>
                                          <label class = "hour-slot" for="advisor_hours_<%= slot %>_<%= date.strftime('%Y-%m-%d') %>">
                                            <div class="block">
                                              <div class="time w-full">-</div>
                                            </div>
                                          </label>
                                        <% end %>
                                      </li>
                                    <% end %>
                                  <% end %>
                                </ul>
                              </div>
                            <% end %>
                            <i class="arrow fa-solid fa-arrow-right" id="right"></i>
                          </div>
                        </div>
                        <div class="voir-moins">
                          <p id="voir-moins">Voir moins</p>
                          <i class="fleche fa-solid fa-greater-than"></i>
                        </div>
                      </div>
                      <%# <div class="mb-6">
                          <input type="date" placeholder="01/01/2024" name="date"
                                  class="w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200" oninput="this.className = 'w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200'" />
                      </div>
                      <div class="mb-6">
                          <input type="time" placeholder="14:30" name="time"
                                  class="w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200" oninput="this.className = 'w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200'" />
                      </div> %>
                  </div>

                  <!-- step three -->
                  <div class="step">
                    <p class="recap text-md text-gray-700 leading-tight text-center">Your Recap</p>
                    <div class="infos-recap">
                      <p id="appointment-type"></p>
                      <p id="rdv"></p>
                    </div>
                    <div class="recap">
                      <div class=" mb-6">
                        <input type="text" placeholder="First name" name="firstname"
                              class="w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200" oninput="this.className = 'w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200'" />
                      </div>
                      <div class=" mb-6">
                        <input type="text" placeholder="Last name" name="lastname"
                              class="w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200" oninput="this.className = 'w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200'" />
                      </div>
                      <div class=" mb-6">
                        <input type="text" placeholder="Mobile" name="mobile"
                              class="w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200" oninput="this.className = 'w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200'" />
                      </div>
                    </div>
                  </div>

                  <!-- Step Four -->
                  <%# <div class="step">
                    <h3>Merci d'avoir pris rendez-vous avec RTV</h3>
                  </div> %>

                  <!-- start previous / next buttons -->
                  <div class="form-footer flex gap-3">
                      <button type="button" id="prevBtn" class="flex-1 focus:outline-none border border-gray-300 py-2 px-5 rounded-lg shadow-sm text-center text-gray-700 text-lg">Previous</button>
                      <button type="button" id="nextBtn" class="flex-1 border border-transparent focus:outline-none p-3 rounded-md text-center text-white  text-lg">Next</button>
                      <input type="submit" id="submitBtn" value="Submit" class="flex-1 border border-transparent focus:outline-none p-3 rounded-md text-center text-white text-lg" style="display: none;">
                  </div>
                <% end  %>
                <!-- end previous / next buttons -->
              <% end %>
              <%# <button class="next-step-button text-white inline-flex w-full justify-center bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                  Next step
              </button> %>
          </div>
      </div>
  </div>

  <%= javascript_import_module_tag "script" %>
  <%= javascript_import_module_tag "calendar" %>
  <%= javascript_import_module_tag "recap" %>

app/views/pages/advisors.html.erb
<div class="container">
  <h1>Pages#advisors</h1>
  <p>Find me in app/views/pages/advisors.html.erb</p>

  <h2>Welcome</h2>
  <%= "#{current_advisor.first_name} - #{current_advisor.last_name}"%>
  <br>
  <br>
  <%= link_to "create an appointment type", new_advisor_appointment_type_path(current_advisor.id)%>

  <div class="container mt-4">
    <div class="row">
      <% current_advisor.appointment_types.each do |appointment_type| %>
        <div class="col-sm">
          <div class="card-product">
            <img src="https://source.unsplash.com/random/?bike" alt="Bike">
            <div class="appoint-info">
              <h2><%= appointment_type.name %></h2>
              <h6><%= appointment_type.duration %> minutes</h6>
              <p><%= appointment_type.description %></p>
            </div>
          </div>
        </div>
      <% end  %>
    </div>
  </div>
<br>
  <h2 class="mt-3">Manage your Availabilities</h2>
  <%= link_to "fill in your availabilities", new_advisor_availability_path(current_advisor) %>
   <%# <%= link_to "See your availabilities", availabilities_path %>
     <table class="table table-hover table-dark">
    <thead>
      <tr>
        <th scope="col">Days</th>
        <th scope="col">Is working </th>
        <th scope="col">Start Time</th>
        <th scope="col">End Time</th>
        <th scope="colspan=2"></th>


      </tr>
    </thead>

    <tbody>
    <% current_advisor.availabilities.each do |availability| %>
      <tr>
        <td>Monday</td>
        <td><%= availability.monday %></td>
        <td><%= availability.start_time.strftime('%H:%M') %></td>
        <td><%= availability.end_time.strftime('%H:%M')%></td>
        <td><%= link_to 'Edit', edit_advisor_availability_path(advisor_id: availability.advisor_id, id: availability.id) %></td>
      </tr>
      <tr>
        <td>Tuesday</td>
        <td><%= availability.tuesday %></td>
        <td><%= availability.start_time.strftime('%H:%M') %></td>
        <td><%= availability.end_time.strftime('%H:%M')%></td>
        <td><%= link_to 'Edit', edit_advisor_availability_path(advisor_id: availability.advisor_id, id: availability.id) %></td>
      </tr>
      <tr>
        <td>Wednesday</td>
        <td><%= availability.wednesday %></td>
        <td><%= availability.start_time.strftime('%H:%M') %></td>
        <td><%= availability.end_time.strftime('%H:%M')%></td>
        <td><%= link_to 'Edit', edit_advisor_availability_path(advisor_id: availability.advisor_id, id: availability.id) %></td>
      </tr>
      <tr>
        <td>Thursday</td>
        <td><%= availability.thursday %></td>
        <td><%= availability.start_time.strftime('%H:%M') %></td>
        <td><%= availability.end_time.strftime('%H:%M')%></td>
        <td><%= link_to 'Edit', edit_advisor_availability_path(advisor_id: availability.advisor_id, id: availability.id) %></td>
      </tr>
      <tr>
        <td>Friday</td>
        <td><%= availability.friday %></td>
        <td><%= availability.start_time.strftime('%H:%M') %></td>
        <td><%= availability.end_time.strftime('%H:%M')%></td>
        <td><%= link_to 'Edit', edit_advisor_availability_path(advisor_id: availability.advisor_id, id: availability.id) %></td>
      </tr>
      <tr>
        <td>Saturday</td>
        <td><%= availability.saturday %></td>
        <td><%= availability.start_time.strftime('%H:%M') %></td>
        <td><%= availability.end_time.strftime('%H:%M')%></td>
        <td><%= link_to 'Edit', edit_advisor_availability_path(advisor_id: availability.advisor_id, id: availability.id) %></td>
      </tr>
      <tr>
        <td>Sunday</td>
        <td><%= availability.sunday %></td>
        <td><%= availability.start_time.strftime('%H:%M') %></td>
        <td><%= availability.end_time.strftime('%H:%M')%></td>
        <td><%= link_to 'Edit', edit_advisor_availability_path(advisor_id: availability.advisor_id, id: availability.id) %></td>
      </tr>
    <% end  %>
    </tbody>
  </table>

<br>
  <h2 class="mt-3">Manage your Appointments</h2>
  <%= link_to 'My appointments', advisor_appointments_path(current_advisor) %>
  <table class="table table-hover table-dark">
    <thead>
      <tr>
        <th scope="col">User ID</th>
        <th scope="col">Status</th>
        <th scope="col">Prénom</th>
        <th scope="col">Nom</th>
        <th scope="col">Téléphone</th>
        <th scope="col">Date</th>
        <th scope="col">Début</th>
        <th scope="col">Fin</th>
        <th scope="col">Type de RDV</th>
        <th scope="col">Durée du RDV</th>
      </tr>
    </thead>
    <tbody>
      <tr>
      <% current_advisor.appointments.each do |appointment| %>
        <td><%= appointment.user_id %></td>
        <td>
          <%= form_with model: appointment, url: update_status_appointment_path(appointment), method: :patch do |f| %>
            <%= f.select :status, Appointment.statuses.map{|key, value| [key.humanize, key]}, selected: appointment.status %>
            <%= f.submit "Update satus", class: "status" %>
          <% end %>
        </td>
        <td><%= appointment.first_name %></td>
        <td><%= appointment.last_name %></td>
        <td><%= appointment.mobile%></td>
        <td><%= appointment.date.strftime('%a-%d-%b-%Y') %></td>
        <td><%= appointment.advisor_hours %></td>
        <td><%= appointment.end_time.strftime('%H:%M')%></td>
        <td><%= appointment.appointment_type.name %></td>
        <td><%= appointment.appointment_type.duration %> min</td>
      </tr>
      <% end %>
    </tbody>
</table>

</div>

app/views/pages/home.html.erb
<div class= "bg-image">
  <div class="container-info container mx-auto">
    <h2 id="pvu">L'expertise des vélocistes en un click !</h1>
    <h2>Réservez - Réprarez - Roulez</h4>
    <br>
    <form id="search-cities">
      <div class="form-group">
        <label for="city-name" class="form-label">Chercher une ville </label>
        <div class="d-flex">
          <input type="text" id="city-name" class="form-input" placeholder="Paris, Nantes, Bordeaux...">
          <input type="submit" value="Rechercher" class="btn-form">
        </div>
      </div>
    </form>
  </div>
  <%# <%= image_tag("velo-2.png") %>
</div>

 <div class="container mt-4">
    <div class="grid grid-cols-4 gap-4">
      <% @advisors.each do |advisor| %>
        <div class="card-advisor">
          <img src="https://source.unsplash.com/random/?portrait" alt="Advisors">
          <h2 id="advisor-name"><%= "#{advisor.first_name} #{advisor.last_name}" %></h2>
          <h6><%= advisor.speciality%></h6>
          <p id="loc"><%= advisor.address%>, <strong><%= advisor.city %></strong></p>
          <div class="advisor-info">
            <p id="bio"><%= advisor.bio %></p>
          </div>
          <div class="parent-rdv">
            <%= link_to "prendre rendez-vous", show_advisor_path(advisor), class: "rdv" %>
          </div>
        </div>
      <% end  %>
    </div>
  </div>
</div>


<script>
  let advisors = <%= @advisors.to_json.html_safe %>;
</script>

<%= javascript_import_module_tag "search" %>

app/views/pages/show_advisor.html.erb
<h1 class="text-lime-400/100">SHOW de L'ADVISOR</h1>

<div class="container">
  <div class="advisor-appoint">
    <img src="https://source.unsplash.com/random/?portrait" alt="Advisor">
    <div class="advisor-inf">
      <h2><%= "#{@advisor.first_name} #{@advisor.last_name}" %></h2>
      <h4><%= @advisor.bio %></h4>
    </div>
  </div>

  <%# <%= link_to "Make an appointment", new_advisor_appointment_path(advisor_id: @advisor.id) %>
  <%= link_to 'New Appointment Test', new_advisor_appointment_path(@advisor) %>
  <button data-modal-target="select-modal" data-modal-toggle="select-modal" id= "my-modal-btn" class=" block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button">
      Make An Appointment
  </button>

  <!-- Main modal -->
  <div id="select-modal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
      <div class="largeur-modal relative p-4 w-full max-w-2xl max-h-full">
          <!-- Modal content -->
          <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
              <!-- Modal header -->
              <div class="flex items-center justify-evenly p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                  <div class="form-header flex gap-3 text-xs text-center">
                    <span class="stepIndicator  flex-1 pb-8 relative">Appointment </span>
                    <span class="stepIndicator  flex-1 pb-8 relative">Date </span>
                    <span class="stepIndicator  flex-1 pb-8 relative">Recap</span>
                  </div>
                  <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm h-8 w-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="select-modal">
                      <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                      </svg>
                      <span class="sr-only">Close modal</span>
                  </button>
              </div>
              <!-- Modal body -->
              <%# <form id="appointmentForm" class="p-12 shadow-md rounded-2xl bg-white mx-auto border-solid border-2 border-gray-100 mb-8" action="#!"> %>
              <%= form_for(Appointment.new, url: advisor_appointments_path(@advisor), id:"appointmentForm", class:"p-12 shadow-md rounded-2xl bg-white mx-auto border-solid border-2 border-gray-100 mb-8", action:"#!") do |f| %>
                <div class="step p-4 md:p-5">
                    <p class="text-gray-500 dark:text-gray-400 mb-4">Select your appointment type:</p>
                    <ul class="space-y-4 mb-4">
                      <% @appointment_types.each do |appointment_type| %>
                        <li>
                            <%= f.radio_button :appointment_type_id, appointment_type.id, id: "appointment_type_#{appointment_type.id}", class: "appointment-radio hidden" %>
                            <label for="appointment_type_<%=appointment_type.id%>" class="appointment-label inline-flex items-center justify-between w-full p-5 text-gray-900 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-500 hover:text-gray-900 hover:bg-gray-100 dark:text-white dark:bg-gray-600 dark:hover:bg-gray-500">
                                <div class="block">
                                    <div class="w-full text-lg font-semibold"><%= appointment_type.name %></div>
                                    <div class="w-full text-gray-500 dark:text-gray-400"><%= appointment_type.duration %> min</div>
                                </div>
                                <svg class="w-4 h-4 ms-3 rtl:rotate-180 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/></svg>
                            </label>
                        </li>
                      <% end %>
                    </ul>
                </div>

                <!-- step two -->
                <div class="step">
                    <p class="text-md text-gray-700 leading-tight text-center mt-8 mb-2">Select your date</p>
                    <div class="calendar" id="calendar">

                      <div class="week-days-container">
                        <div class="days-container">
                          <i class="arrow fa-solid fa-arrow-left" id="left"></i>
                          <% @week_dates.each do |day_name, date| %>
                            <div class="day-selector">
                              <div class="date-info">
                                <p class="day-pick"><%= day_name %></p>
                                <p class="date"><%= date.strftime('%d-%b') %></p>
                              </div>
                              <ul class="time-slots">
                                <% @advisor.availabilities.each do |availability| %>
                                  <% availability.time_slots_day(date).each do |slot| %>
                                    <li>
                                      <% if slot != "none" %>
                                        <%= f.radio_button :advisor_hours, slot, id: "advisor_hours_#{slot}_#{date.strftime('%Y-%m-%d')}", class: "advisor-hours" %>
                                        <label class="hour-slot" for="advisor_hours_<%= slot %>_<%= date.strftime('%Y-%m-%d') %>">
                                          <div class="block">
                                            <div class="time w-full"><%= slot %></div>
                                          </div>
                                        </label>
                                      <% else %>
                                        <%= f.radio_button :advisor_hours, slot, id: "advisor_hours_#{slot}_#{date.strftime('%Y-%m-%d')}", class: "none-advisor-hours", disabled: :true %>
                                        <label class = "hour-slot" for="advisor_hours_<%= slot %>_<%= date.strftime('%Y-%m-%d') %>">
                                          <div class="block">
                                            <div class="time w-full">-</div>
                                          </div>
                                        </label>
                                      <% end %>
                                    </li>
                                  <% end %>
                                <% end %>
                              </ul>
                            </div>
                          <% end %>
                          <%= f.hidden_field :date, id: 'appointment_date' %>
                          <i class="arrow fa-solid fa-arrow-right" id="right"></i>
                        </div>
                      </div>
                      <div class="voir-moins">
                        <p>Voir moins</p>
                        <i class="fleche fa-solid fa-greater-than"></i>
                      </div>
                    </div>
                    <%# <div class="mb-6">
                        <input type="date" placeholder="01/01/2024" name="date"
                                class="w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200" oninput="this.className = 'w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200'" />
                    </div>
                    <div class="mb-6">
                        <input type="time" placeholder="14:30" name="time"
                                class="w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200" oninput="this.className = 'w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200'" />
                    </div> %>
                </div>

                <!-- step three -->
                <div class="step">
                  <p class="recap text-md text-gray-700 leading-tight text-center">Your Recap</p>
                  <div class="infos-recap">
                    <p id="appointment-type"></p>
                    <p id="rdv"></p>
                  </div>
                  <div class="recap">
                    <div class=" mb-6">
                      <%= f.text_field :first_name, placeholder: "First Name", class: "w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200", oninput: "this.className = 'w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200' " %>
                    </div>
                    <div class=" mb-6">
                      <%= f.text_field :last_name, placeholder: "Last Name", class: "w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200", oninput: "this.className = 'w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200' " %>
                    </div>
                    <div class=" mb-6">
                      <%= f.text_field :mobile, placeholder: "Mobile", class: "w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200", oninput: "this.className = 'w-full px-4 py-3 rounded-md text-gray-700 font-medium border-solid border-2 border-gray-200' " %>
                    </div>
                  </div>
                </div>

                <!-- Step Four -->
                <%# <div class="step">
                  <h3>Merci d'avoir pris rendez-vous avec RTV</h3>
                </div> %>

                <!-- start previous / next buttons -->
                <div class="form-footer flex gap-3">
                    <button type="button" id="prevBtn" class="flex-1 focus:outline-none border border-gray-300 py-2 px-5 rounded-lg shadow-sm text-center text-gray-700 text-lg">Previous</button>
                    <button type="button" id="nextBtn" class="flex-1 border border-transparent focus:outline-none p-3 rounded-md text-center text-white  text-lg">Next</button>
                    <input type="submit" id="submitBtn" value="Submit" class="flex-1 border border-transparent focus:outline-none p-3 rounded-md text-center text-white text-lg" style="display: none;">
                </div>

                <!-- end previous / next buttons -->
              <% end %>
              <%# <button class="next-step-button text-white inline-flex w-full justify-center bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                  Next step
              </button> %>
          </div>
      </div>
  </div>

  <%= javascript_import_module_tag "script" %>
  <%= javascript_import_module_tag "calendar" %>
  <%= javascript_import_module_tag "recap" %>

app/views/pages/users.html.erb
<h1>Pages#users</h1>
<p>Find me in app/views/pages/users.html.erb</p>