config/routes.rb
Rails.application.routes.draw do
  # get 'pages/dashboard'
  # get 'pages/users'
  get 'pages/advisors'
  get 'pages/show_advisor/:id', to: 'pages#show_advisor', as: 'show_advisor'
  # get 'users/advisors'

  devise_for :advisors, controllers: {
    sessions: 'advisors/sessions',
    registrations: 'advisors/registrations'
  }

  resources :advisors do
    resources :appointment_types
  end


  resources :appointments do
    patch :update_status, on: :member
  end

  resources :advisors do
    resources :appointment_types
    resources :appointments
    resources :availabilities
  end



  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :advisor
  # has_many :appointments, through :advisor
  # validates :day_of_week, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true

  before_validation :set_default_times, on: :create


  def covers_day?(date)
    day_of_week = date.strftime('%A').downcase
    self[day_of_week]
  end


  def time_slots_day(date)

    all_slots = []

    advisor_availabilities = Availability.where(advisor_id: self.advisor_id)

    day_availabilities = advisor_availabilities.select { |availability| availability.covers_day?(date) }

    appointments_date = Appointment.where(advisor_id: self.advisor_id, date: date.beginning_of_day..date.end_of_day)

    appointment_hours = appointments_date.map(&:advisor_hours)

    Rails.logger.info "Nombre de rendez-vous trouvés pour la date #{date} : #{appointments_date.count} à #{appointment_hours}"

    if day_availabilities.empty?
      # Si day_availabilities est vide ou Si un utilisateur a déjà réservé un créneau, on ne peut pas le réserver
      # On ajoute donc un créneau "none" pour chaque créneau horaire réservé
      # On récupère les créneaux horaires réservés via appointment.advisor_hours

      typical_start = advisor_availabilities.map(&:start_time).min
      typical_end = advisor_availabilities.map(&:end_time).max

      num_slots = ((typical_end - typical_start) / 30.minutes).to_i

     num_slots.times{ all_slots << "none" }

    else
      start_day = day_availabilities.map(&:start_time).min
      end_day = day_availabilities.map(&:end_time).max

      current_time = start_day

      while current_time < end_day

        # Ajout du créneau horaire au format HH:MM
        slot = current_time.strftime('%H:%M')

        if appointment_hours.include?(slot)
          all_slots << "none"
        else
          all_slots << slot
        end

        current_time += 30.minutes
      end
    end
    all_slots
  end


  private

  def set_default_times
    self.start_time ||= '09:00'
    self.end_time ||= '18:00'
  end
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  before_action :authenticate_advisor!
  before_action :set_availability, only: %i[edit update]
  before_action :set_advisor, only: %i[index show new create edit]

  def index

    @availabilities = @advisor.availabilities
  end

  def show
  end

  def new
    @availability = @advisor.availabilities.new
    @availability.start_time = '09:00' if @availability.start_time.blank?
    @availability.end_time = '19:00' if @availability.end_time.blank?
  end

  def create
    @availability = @advisor.availabilities.new(availability_params)
    if @availability.save
      redirect_to pages_advisors_path, notice: 'Availabilities save'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @availability.update(availability_params)
      redirect_to pages_advisors_path, notice: 'Availabilities updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end


  private

  def set_advisor
    @advisor = Advisor.find(params[:advisor_id])
  end

  def set_availability
    @availability = current_advisor.availabilities.find(params[:id])
  end

  def availability_params
    params.require(:availability).permit(:monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday, :start_time, :end_time)
  end
end

app/views/availabilities/_form.html.erb
<%= form_with(model: [@advisor, availability], local: true) do |form| %>

  <div class="filed">
    <%= form.label :monday %>
    <%= form.check_box :monday%>
  </div>

  <div class="filed">
    <%= form.label :start_time %>
    <%= form.time_select :start_time, {default: {hour: '09', minute: '00'}} %>
  </div>

  <div class="filed">
    <%= form.label :end_time%>
    <%= form.time_select :end_time, {default: {hour: '19', minute: '00'}}  %>
  </div>


  <div class="filed">
    <%= form.label :tuesday %>
    <%= form.check_box :tuesday %>
  </div>

  <div class="filed">
    <%= form.label :start_time %>
    <%= form.time_select :start_time, {default: {hour: '09', minute: '00'}} %>
  </div>

  <div class="filed">
    <%= form.label :end_time%>
    <%= form.time_select :end_time, {default: {hour: '19', minute: '00'}} %>
  </div>



  <div class="filed">
    <%= form.label :wednesday %>
    <%= form.check_box :wednesday %>
  </div>

  <div class="filed">
    <%= form.label :start_time %>
    <%= form.time_select :start_time, {default: {hour: '09', minute: '00'}} %>
  </div>

  <div class="filed">
    <%= form.label :end_time%>
    <%= form.time_select :end_time, {default: {hour: '19', minute: '00'}} %>
  </div>



  <div class="filed">
    <%= form.label :thursday %>
    <%= form.check_box :thursday %>
  </div>

  <div class="filed">
    <%= form.label :start_time %>
    <%= form.time_select :start_time, {default: {hour: '09', minute: '00'}} %>
  </div>

  <div class="filed">
    <%= form.label :end_time%>
    <%= form.time_select :end_time, {default: {hour: '19', minute: '00'}} %>
  </div>



  <div class="filed">
    <%= form.label :friday %>
    <%= form.check_box :friday %>
  </div>

  <div class="filed">
    <%= form.label :start_time %>
    <%= form.time_select :start_time, {default: {hour: '09', minute: '00'}} %>
  </div>

  <div class="filed">
    <%= form.label :end_time%>
    <%= form.time_select :end_time, {default: {hour: '19', minute: '00'}} %>
  </div>



  <div class="filed">
    <%= form.label :saturday %>
    <%= form.check_box :saturday %>
  </div>

  <div class="filed">
    <%= form.label :start_time %>
    <%= form.time_select :start_time, {default: {hour: '09', minute: '00'}} %>
  </div>

  <div class="filed">
    <%= form.label :end_time%>
    <%= form.time_select :end_time, {default: {hour: '19', minute: '00'}} %>
  </div>


  <div class="filed">
    <%= form.label :sunday %>
    <%= form.check_box :sunday %>
  </div>

  <div class="filed">
    <%= form.label :start_time %>
    <%= form.time_select :start_time, {default: {hour: '09', minute: '00'}} %>
  </div>

  <div class="filed">
    <%= form.label :end_time%>
    <%= form.time_select :end_time, {default: {hour: '19', minute: '00'}} %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/availabilities/edit.html.erb
<h1> Edit Availabilities</h1>

<div class="container">
  <%= render 'form', availability: @availability %>

  <%= link_to "Back", pages_advisors_path %>
</div>

app/views/availabilities/index.html.erb
<h1>Your availabilities</h1>

<div class="container">
  <table class="table table-hover table-dark">
    <thead>
      <tr>
        <th scope="col">Days</th>
        <th scope="col">Is working </th>
        <th scope="col">Start Time</th>
        <th scope="col">End Time</th>
        <th scope="colspan=2"></th>


      </tr>
    </thead>

    <tbody>
    <% @availabilities.each do |availability| %>
      <tr>
        <td>Monday</td>
        <td><%= availability.monday %></td>
        <td><%= availability.start_time %></td>
        <td><%= availability.end_time%></td>
        <td><%= link_to 'Edit', edit_availability_path(availability) %></td>
      </tr>
      <tr>
        <td>Tuesday</td>
        <td><%= availability.tuesday %></td>
        <td><%= availability.start_time %></td>
        <td><%= availability.end_time%></td>
        <td><%= link_to 'Edit', edit_availability_path(availability) %></td>
      </tr>
      <tr>
        <td>Wednesday</td>
        <td><%= availability.wednesday %></td>
        <td><%= availability.start_time %></td>
        <td><%= availability.end_time%></td>
        <td><%= link_to 'Edit', edit_availability_path(availability) %></td>
      </tr>
      <tr>
        <td>Thursday</td>
        <td><%= availability.thursday %></td>
        <td><%= availability.start_time %></td>
        <td><%= availability.end_time%></td>
        <td><%= link_to 'Edit', edit_availability_path(availability) %></td>
      </tr>
      <tr>
        <td>Friday</td>
        <td><%= availability.friday %></td>
        <td><%= availability.start_time %></td>
        <td><%= availability.end_time%></td>
        <td><%= link_to 'Edit', edit_availability_path(availability) %></td>
      </tr>
      <tr>
        <td>Saturday</td>
        <td><%= availability.saturday %></td>
        <td><%= availability.start_time %></td>
        <td><%= availability.end_time%></td>
        <td><%= link_to 'Edit', edit_availability_path(availability) %></td>
      </tr>
      <tr>
        <td>Sunday</td>
        <td><%= availability.sunday %></td>
        <td><%= availability.start_time %></td>
        <td><%= availability.end_time%></td>
        <td><%= link_to 'Edit', edit_availability_path(availability) %></td>
      </tr>
    <% end  %>
    </tbody>
  </table>

  
</div>

app/views/availabilities/new.html.erb
<h1>PAGES NEW AVAILABILITY</h1>

<div class="container">
  <%= render 'form', availability: @availability %>

  <%= link_to "Back", pages_advisors_path %>
</div>